name: disposing
description: disposing package for flutter.
repository: https://github.com/SKKbySSK/dart_disposing/tree/master/disposing_flutter
publish_to: none

version: 1.0.3+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0
